try: 
#     a = 5 / 0
# except Exception as e:
#     print(f"Error happened: {e}")